### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by ajaxmonk** [chef/knife-linode#48]
Getting this error when trying 
gem install knife-linode

ERROR:  Error installing knife-linode:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'

-- Ubuntu
-- Chef 12.0
-- Ruby 2.0

**Comment by jdblack** [comment]
Try installing the ruby-dev package for your system.
